# Generated by Django 6.0 on 2025-12-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_person_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='phone_number',
            field=models.CharField(default=439035098, max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
